### ISSUE TITLE
Origin problem in sliceViewer

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtalTools#187]
I have an issue with the `sliceViewer` tool (see snapshot): the origin of the Vol file is not taken into account correctly in the slice panes (I'll send you the Catenoid vol file by email).

![capture d ecran 2014-11-03 a 14 22 32](https://cloud.githubusercontent.com/assets/700165/4884814/4c05e402-636f-11e4-95dd-3fcef118c3ad.png)

**Comment by kerautret** [comment]
That corrected in https://github.com/DGtal-team/DGtal/pull/989 closing..
