### ISSUE TITLE
3dCurvatureViewer: ensure that -e is specified in --exportOnly

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtalTools#190]
when using --exportOnly option, we should make sure that a "--export" is given.

**Comment by jlevallois** [comment]
I look at this

**Comment by kerautret** [comment]
also closing ;)

**Comment by dcoeurjo** [comment]
Hi @jlevallois and @kerautret , I think this issue still exists in the master. I'm reopening it

**Comment by dcoeurjo** [comment]
Okay my issue is different. closing this one
