### ISSUE TITLE
bug converters/freeman2sdp option oneline

### ISSUE THREAD

**Issue by ngophuc** [DGtal-team/DGtalTools#277]
There is a space missing for writing sdp with option -o (--oneLine)

L157: std::cout << vectPts.at(k)[0] << " "<< vectPts.at(k)[1];
   => std::cout << vectPts.at(k)[0] << " "<< vectPts.at(k)[1]**<< " "**;

**Comment by kerautret** [comment]
thanks @ngophuc  that corrected you can have a look on the PR to confirm that fine ? #278
(on my branch FixFreeman2sdpOneline)

**Comment by kerautret** [comment]
merged so fixed ;)
