### ISSUE TITLE
Travis script does not compile the code

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtalTools#307]
it looks like the travis script does not compile the code. See #306  for instance.

Are you sure we need to compile boost ? The travis VM has been upgraded and maybe the packages boost is fine (as it is for DGtal).

**Comment by dcoeurjo** [comment]
it seems that only one target (out of for) actually builds the code.

**Comment by dcoeurjo** [comment]
(Debug)

**Comment by kerautret** [comment]
@dcoeurjo sorry I miss your issue 👀
I don't see anymore the travis or appveyor tools like in the last PR [#308](https://github.com/DGtal-team/DGtalTools/pull/308)
Perhaps you have change something for testing ?

**Comment by kerautret** [comment]
>Are you sure we need to compile boost ? The travis VM has been upgraded and maybe the packages boost is fine (as it is for DGtal)
Yes but the difference is mainly from the boost program option, I look it

**Comment by kerautret** [comment]
closing fixed
