### ISSUE TITLE
Wrong version of DGtal required in the cmakelist file

### ISSUE THREAD

**Issue by copyme** [DGtal-team/DGtalTools#330]
So, there is `FIND_PACKAGE(DGtal 0.9.3 REQUIRED)`, but I think that it should be `FIND_PACKAGE(DGtal 0.9.4 REQUIRED)`

**Comment by kerautret** [comment]
thanks corrected.

**Comment by copyme** [comment]
@kerautret @dcoeurjo I think we are good for 0.9.4.1.

**Comment by kerautret** [comment]
yes thanks @copyme
