### ISSUE TITLE
moc generation failed

### ISSUE THREAD

**Issue by copyme** [DGtal-team/DGtalTools#333]
While compiling DGtal 0.9.4 or the current master:

[ 92%] Generating ui_sliceViewer.h
[ 93%] Generating moc_sliceViewer.cxx
moc: Cannot open options file specified with @
Usage: moc [options] <header-file>
  -o<file>           write output to file rather than stdout
  -I<dir>            add dir to the include path for header files
  -E                 preprocess only; do not generate meta object code
  -D<macro>[=<def>]  define macro, with optional definition
  -U<macro>          undefine macro
  -i                 do not generate an #include statement
  -p<path>           path prefix for included file
  -f[<file>]         force #include, optional file name
  -nn                do not display notes
  -nw                do not display warnings
  @<file>            read additional options from file
  -v                 display version of moc
visualisation/CMakeFiles/sliceViewer.dir/build.make:62: recipe for target 'visualisation/moc_sliceViewer.cxx' failed
make[2]: *** [visualisation/moc_sliceViewer.cxx] Error 1
CMakeFiles/Makefile2:2762: recipe for target 'visualisation/CMakeFiles/sliceViewer.dir/all' failed
make[1]: *** [visualisation/CMakeFiles/sliceViewer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 94%] Linking CXX executable 3dImageViewer
[ 94%] Built target 3dImageViewer
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kerautret** [comment]
@copyme thanks, which qt version do you have? Have you changed of QT version ?

**Comment by kerautret** [comment]
have you check that you have any accent in your path ?
It could be a bug of qt.

**Comment by kerautret** [comment]
or space

**Comment by copyme** [comment]
Qt version 4.8.6. I tired to use qmake-qt5 but it tells me that this version of Qt is not supported or something like that.

**Comment by copyme** [comment]
@kerautret thanks for the hints. Indeed, I had a French accent in the path. I moved the project and then I could compile.
