### ISSUE TITLE
How to write STEP file from 3D Data/Surf ?

### ISSUE THREAD

**Issue by selvakarna** [DGtal-team/DGtalTools#357]
How to write STEP file from 3D Data/Surf ?

**Comment by kerautret** [comment]
@selvakarna  sorry for the delay, actually the STEP format is not handled in the tools. 
But if you want you can extract the surface I suggest you to use [volBoundary2obj](https://github.com/DGtal-team/DGtalTools/blob/master/converters/volBoundary2obj.cpp) that allows to get a std .obj mesh
