### ISSUE TITLE
Problem with mathjax in the doc

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtalTools#361]
https://dgtal.org/doc/tools/nightly/moduleAT.html

BTW: when building the doc for DGtal, the tag names of DGtalTools pages correspond to the 0.9.4 version of DGtalTools.

**Comment by kerautret** [comment]
Thanks @dcoeurjo I look it this week! ;)

**Comment by kerautret** [comment]
fixed like the links ;)
