### ISSUE TITLE
Generate SDP file from an contour image

### ISSUE THREAD

**Issue by julianakuei** [DGtal-team/DGtalTools#362]
I want to generate "sdp file" from a contour image (see the attachments), but I saw the DGtal library only support "freeman to sdp"; the problem is that the freeman chain data only can extract the outside contour, so the inside contour will be missed.
I am wondering if there are any tool that can generate sdp file for this case?

![22](https://user-images.githubusercontent.com/25919263/69224200-1526b380-0bb7-11ea-9a1d-adcbc3932df7.jpg)

**Comment by kerautret** [comment]
@julianakuei Thanks you for your feedback, (really for the delay !). Perhaps you have found already a solution but here are the steps that you can do with the DGtalTools:
`img2freeman -i tmp.pgm  > tmp.fc
freeman2sdp -i tmp.fc -o > contourS.sdp
`
You will obtain a set of several concurs:
[contourS.sdp.gz](https://github.com/DGtal-team/DGtalTools/files/4624600/contourS.sdp.gz)

If you want you can also check the result that by using the tools [displaySet2dPts](https://github.com/DGtal-team/DGtalTools-contrib/blob/master/visualisation/displaySet2dPts.cpp) from the [DGtalTools-contrib](https://github.com/DGtal-team/DGtalTools-contrib)
Like: 
`displaySet2dPts -i  contourS.sdp -o titi.eps `
you will obtain such a result:

![titi](https://user-images.githubusercontent.com/772865/81863948-3d8ed980-956c-11ea-91c6-3b6100e30d6c.png)
Help that it can be useful for you !
