### ISSUE TITLE
3dLocalEstimators errors

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtalTools#382]
I obtain several errors after un commenting the CMakelists of estimators part:
<img width="1417" alt="Capture d’écran 2020-06-14 à 18 05 53" src="https://user-images.githubusercontent.com/772865/84598262-c6e64400-ae69-11ea-9a1c-6e574409c3df.png">
<img width="1427" alt="Capture d’écran 2020-06-14 à 18 07 05" src="https://user-images.githubusercontent.com/772865/84598269-dc5b6e00-ae69-11ea-9d5d-0a023cd4c0d7.png">

**Comment by kerautret** [comment]
@dcoeurjo I started to fix the first one: #383 
If you have an idea of the second one (mentioned in LocalEstimatorFromSurfelFunctorAdapter.h)

**Comment by rolanddenis** [comment]
@kerautret At first glance, it may come from the stricter rules implemented in https://github.com/DGtal-team/DGtal/pull/1345 (also see #347) concerning conversion between `PointVector` with different coordinate types.

E.g. the embedder may returns a point with real coordinates while the metric accepts integer coordinates.
