### ISSUE TITLE
Bugs in Contourgenerator and freeman2img Tools.

### ISSUE THREAD

**Issue by lamaydt1986** [DGtal-team/DGtalTools#386]
Contourgenerator Tool:
-g [ --gridstep ] arg (=1)       Gridstep for the digitization
-f [ --format ] arg (=pts)       Output format:
List of pointel coordinates {pts}
Freman chaincode Vector {fc}
-o [ --outputGeometry ] arg      Base name of the file containing the shape
geometry (points, tangents, curvature)
Those options are still on the website doc while we are not able to use them anymore.
-o now stands for --output( not outputGeometry)
-f doesn't exist anymore it gives the coordinates of points by default and doesn't accept the fc option.
-g is not recognize anymore.
Freeman2img Tool:
We need to precize the min value and max value
":img2freeman -i result.pgm --min 128 --max 255 > contours.fc"
which is not written and described in the doc online.

**Comment by kerautret** [comment]
@lamaydt1986 Thanks I look it

**Comment by kerautret** [comment]
for contourGenerator, It looks fine for me: 
![Capture d’écran 2020-09-12 à 15 26 41](https://user-images.githubusercontent.com/772865/92996573-f65e2880-f50c-11ea-9969-0dd63f1782cd.png)
<img width="675" alt="Capture d’écran 2020-09-12 à 15 26 33" src="https://user-images.githubusercontent.com/772865/92996575-f9591900-f50c-11ea-81f6-22c9916a0678.png">
outputGeometry is well present (perhaps you miss it with shapeGenerator which is different)
For  img2freeman, perhaps no contours are given in your image included between 128 and 255 ? I just detect that "-o" is no more used, I change it in the big PR else it will gives conflicts.

**Comment by kerautret** [comment]
for img2freeman it is changed in upcoming PR in this commit:
https://github.com/DGtal-team/DGtalTools/pull/373/commits/30361aa3648db575271d676b793afa7121a4baa8
