### ISSUE TITLE
Typo in 3dCompSurfelData.cpp

### ISSUE THREAD

**Issue by copyme** [DGtal-team/DGtalTools#427]
If I am not mistaken, there is a little bug in `3dCompSurfelData`, there is

 `app.add_flag("-n,--noWindows","Don't display Viewer windows." );` 
should be 
`app.add_flag("-n,--noWindows", noWindows,"Don't display Viewer windows." );`

**Comment by dcoeurjo** [comment]
Agree. Thx for the bug report

**Comment by dcoeurjo** [comment]
Agree. Thx for the bug report @copyme
