### ISSUE TITLE
vol2slice exports too many slices

### ISSUE THREAD

**Issue by dcoeurjo** [DGtal-team/DGtalTools#428]
When using `vol2slice -i ~/Sources/DGtal/examples/samples/cat10.vol`, I obtain an infinite number of PGM (only the first ten are relevant for the vol file).

I thus have to stop the process

**Comment by dcoeurjo** [comment]
(MacOs, apple mini M1)

**Comment by kerautret** [comment]
Thanks fixed in #439 just a forget in default value from CLI change ;)
